Repository enzomoralesl/FutMobile, pull requests merged in 2020-11, with the labels that each got.

#27 Supportcontact to desenv branch
  .github/workflows/pull_request_futmobile.yml
  src/FutMobile/FutMobile.Tests/obj/Debug/FutMobile.Tests.csproj.CoreCompileInputs.cache
  src/FutMobile/FutMobile.Tests/obj/Debug/FutMobile.Tests.csprojAssemblyReference.cache
  src/FutMobile/FutMobile/Controllers/AccountController.cs
  src/FutMobile/FutMobile/Controllers/RestrictedController.cs
  src/FutMobile/FutMobile/Models/AccountViewModels.cs
  src/FutMobile/FutMobile/Views/Restricted/Ajuda.cshtml
  src/FutMobile/FutMobile/bin/FutMobile.dll
  src/FutMobile/FutMobile/bin/FutMobile.pdb
  src/FutMobile/FutMobile/bin/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.CoreCompileInputs.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.FileListAbsolute.txt
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.GenerateResource.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csprojAssemblyReference.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.dll
  src/FutMobile/FutMobile/obj/Release/FutMobile.pdb
Labels: Component, enhancement

#28 Added a administrator role that can view, edit and delete users, posts and comments.
  src/FutMobile/FutMobile.Tests/bin/Debug/FutMobile.Tests.dll
  src/FutMobile/FutMobile.Tests/bin/Debug/FutMobile.Tests.pdb
  src/FutMobile/FutMobile.Tests/bin/Debug/FutMobile.dll
  src/FutMobile/FutMobile.Tests/bin/Debug/FutMobile.pdb
  src/FutMobile/FutMobile.Tests/obj/Debug/FutMobile.Tests.csproj.CoreCompileInputs.cache
  src/FutMobile/FutMobile.Tests/obj/Debug/FutMobile.Tests.csproj.FileListAbsolute.txt
  src/FutMobile/FutMobile.Tests/obj/Debug/FutMobile.Tests.csprojAssemblyReference.cache
  src/FutMobile/FutMobile.Tests/obj/Debug/FutMobile.Tests.dll
  src/FutMobile/FutMobile.Tests/obj/Debug/FutMobile.Tests.pdb
  src/FutMobile/FutMobile/Context/Contexto.cs
  src/FutMobile/FutMobile/Controllers/AccountController.cs
  src/FutMobile/FutMobile/Controllers/ManageController.cs
  src/FutMobile/FutMobile/FutMobile.csproj
  src/FutMobile/FutMobile/Models/ManageViewModels.cs
  src/FutMobile/FutMobile/Views/Comentarios/Index.cshtml
  src/FutMobile/FutMobile/Views/Manage/DeleteUser.cshtml
  src/FutMobile/FutMobile/Views/Manage/EditUser.cshtml
  src/FutMobile/FutMobile/Views/Manage/Index.cshtml
  src/FutMobile/FutMobile/Views/Manage/ListUsers.cshtml
  src/FutMobile/FutMobile/Views/Posts/Details.cshtml
  src/FutMobile/FutMobile/Views/Posts/Index.cshtml
  src/FutMobile/FutMobile/bin/FutMobile.dll
  src/FutMobile/FutMobile/bin/FutMobile.pdb
  src/FutMobile/FutMobile/obj/Release/DesignTimeResolveAssemblyReferencesInput.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.CoreCompileInputs.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.FileListAbsolute.txt
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.GenerateResource.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csprojAssemblyReference.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.dll
  src/FutMobile/FutMobile/obj/Release/FutMobile.pdb
Labels: Component

#29 Posts page front-end updated
  src/FutMobile/FutMobile/Controllers/ComentariosController.cs
  src/FutMobile/FutMobile/FutMobile.csproj
  src/FutMobile/FutMobile/Views/Comentarios/Create.cshtml
  src/FutMobile/FutMobile/Views/Comentarios/Delete.cshtml
  src/FutMobile/FutMobile/Views/Comentarios/Edit.cshtml
  src/FutMobile/FutMobile/Views/Manage/ListUsers.cshtml
  src/FutMobile/FutMobile/Views/Posts/Create.cshtml
  src/FutMobile/FutMobile/Views/Posts/Delete.cshtml
  src/FutMobile/FutMobile/Views/Posts/Details.cshtml
  src/FutMobile/FutMobile/Views/Posts/Edit.cshtml
  src/FutMobile/FutMobile/Views/Posts/Index.cshtml
  src/FutMobile/FutMobile/Views/Restricted/Ajuda.cshtml
  src/FutMobile/FutMobile/bin/FutMobile.dll
  src/FutMobile/FutMobile/bin/FutMobile.pdb
  src/FutMobile/FutMobile/bin/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  src/FutMobile/FutMobile/obj/Release/DesignTimeResolveAssemblyReferencesInput.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.CoreCompileInputs.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.FileListAbsolute.txt
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.GenerateResource.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csprojAssemblyReference.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.dll
  src/FutMobile/FutMobile/obj/Release/FutMobile.pdb
Labels: Component

#36 Added search by name function to campeonatos and times
  src/FutMobile/FutMobile.Tests/obj/Debug/FutMobile.Tests.csprojAssemblyReference.cache
  src/FutMobile/FutMobile/Controllers/CampeonatosController.cs
  src/FutMobile/FutMobile/Controllers/ComentariosController.cs
  src/FutMobile/FutMobile/Controllers/ManageController.cs
  src/FutMobile/FutMobile/Controllers/PostsController.cs
  src/FutMobile/FutMobile/Controllers/TimesController.cs
  src/FutMobile/FutMobile/FutMobile.csproj
  src/FutMobile/FutMobile/Models/Comentario.cs
  src/FutMobile/FutMobile/Utilities/LogosCamps/Federação_Paulista_de_Futebol_logo.png
  src/FutMobile/FutMobile/Views/Campeonatos/Create.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Delete.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Details.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Edit.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/EspeMotivo.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/EspecificaMotivo.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Index.cshtml
  src/FutMobile/FutMobile/Views/Comentarios/Create.cshtml
  src/FutMobile/FutMobile/Views/Comentarios/Edit.cshtml
  src/FutMobile/FutMobile/Views/Manage/ListUsers.cshtml
  src/FutMobile/FutMobile/Views/Posts/Delete.cshtml
  src/FutMobile/FutMobile/Views/Posts/Details.cshtml
  src/FutMobile/FutMobile/Views/Posts/Index.cshtml
  src/FutMobile/FutMobile/Views/Times/Create.cshtml
  src/FutMobile/FutMobile/Views/Times/Delete.cshtml
  src/FutMobile/FutMobile/Views/Times/Details.cshtml
  src/FutMobile/FutMobile/Views/Times/Edit.cshtml
  src/FutMobile/FutMobile/Views/Times/EspecificaMotivo.cshtml
  src/FutMobile/FutMobile/Views/Times/Index.cshtml
  src/FutMobile/FutMobile/bin/FutMobile.dll
  src/FutMobile/FutMobile/bin/FutMobile.pdb
  src/FutMobile/FutMobile/obj/Release/DesignTimeResolveAssemblyReferencesInput.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.dll
  src/FutMobile/FutMobile/obj/Release/FutMobile.pdb
Labels: enhancement

#37 "Campeonatos" and "Times" front-end updated
  src/FutMobile/FutMobile/FutMobile.csproj
  src/FutMobile/FutMobile/Utilities/LogosCamps/Carioca.png
  src/FutMobile/FutMobile/Utilities/LogosTimes/Corinthians.png
  src/FutMobile/FutMobile/Utilities/LogosTimes/Flamengo.png
  src/FutMobile/FutMobile/Utilities/LogosTimes/Santos.png
  src/FutMobile/FutMobile/Utilities/LogosTimes/palmeiras.png
  src/FutMobile/FutMobile/Views/Campeonatos/Create.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Delete.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Details.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Edit.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/EspecificaMotivo.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Index.cshtml
  src/FutMobile/FutMobile/Views/Restricted/Ajuda.cshtml
  src/FutMobile/FutMobile/Views/Times/Create.cshtml
  src/FutMobile/FutMobile/Views/Times/Delete.cshtml
  src/FutMobile/FutMobile/Views/Times/Details.cshtml
  src/FutMobile/FutMobile/Views/Times/Edit.cshtml
  src/FutMobile/FutMobile/Views/Times/EspecificaMotivo.cshtml
  src/FutMobile/FutMobile/Views/Times/Index.cshtml
  src/FutMobile/FutMobile/bin/FutMobile.dll
  src/FutMobile/FutMobile/bin/FutMobile.pdb
  src/FutMobile/FutMobile/bin/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  src/FutMobile/FutMobile/obj/Release/DesignTimeResolveAssemblyReferencesInput.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.CoreCompileInputs.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.FileListAbsolute.txt
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.GenerateResource.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csprojAssemblyReference.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.dll
  src/FutMobile/FutMobile/obj/Release/FutMobile.pdb
Labels: Component

#38 Pull request to merge Desenv branch to Master on FutProjects - Final Part
  .github/workflows/master_futmobile.yml
  .github/workflows/pull_request_futmobile.yml
  src/FutMobile/FutMobile.Tests/obj/Debug/FutMobile.Tests.csprojAssemblyReference.cache
  src/FutMobile/FutMobile/Controllers/CampeonatosController.cs
  src/FutMobile/FutMobile/Controllers/ComentariosController.cs
  src/FutMobile/FutMobile/Controllers/ManageController.cs
  src/FutMobile/FutMobile/Controllers/PostsController.cs
  src/FutMobile/FutMobile/Controllers/TimesController.cs
  src/FutMobile/FutMobile/FutMobile.csproj
  src/FutMobile/FutMobile/Models/Comentario.cs
  src/FutMobile/FutMobile/Utilities/LogosCamps/Carioca.png
  src/FutMobile/FutMobile/Utilities/LogosCamps/Federação_Paulista_de_Futebol_logo.png
  src/FutMobile/FutMobile/Utilities/LogosTimes/Corinthians.png
  src/FutMobile/FutMobile/Utilities/LogosTimes/Flamengo.png
  src/FutMobile/FutMobile/Utilities/LogosTimes/Santos.png
  src/FutMobile/FutMobile/Utilities/LogosTimes/palmeiras.png
  src/FutMobile/FutMobile/Views/Campeonatos/Create.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Delete.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Details.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Edit.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/EspeMotivo.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/EspecificaMotivo.cshtml
  src/FutMobile/FutMobile/Views/Campeonatos/Index.cshtml
  src/FutMobile/FutMobile/Views/Comentarios/Create.cshtml
  src/FutMobile/FutMobile/Views/Comentarios/Edit.cshtml
  src/FutMobile/FutMobile/Views/Manage/ListUsers.cshtml
  src/FutMobile/FutMobile/Views/Posts/Delete.cshtml
  src/FutMobile/FutMobile/Views/Posts/Details.cshtml
  src/FutMobile/FutMobile/Views/Posts/Index.cshtml
  src/FutMobile/FutMobile/Views/Restricted/Ajuda.cshtml
  src/FutMobile/FutMobile/Views/Times/Create.cshtml
  src/FutMobile/FutMobile/Views/Times/Delete.cshtml
  src/FutMobile/FutMobile/Views/Times/Details.cshtml
  src/FutMobile/FutMobile/Views/Times/Edit.cshtml
  src/FutMobile/FutMobile/Views/Times/EspecificaMotivo.cshtml
  src/FutMobile/FutMobile/Views/Times/Index.cshtml
  src/FutMobile/FutMobile/bin/FutMobile.dll
  src/FutMobile/FutMobile/bin/FutMobile.pdb
  src/FutMobile/FutMobile/bin/Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll
  src/FutMobile/FutMobile/obj/Release/DesignTimeResolveAssemblyReferencesInput.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.CoreCompileInputs.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.FileListAbsolute.txt
  src/FutMobile/FutMobile/obj/Release/FutMobile.csproj.GenerateResource.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.csprojAssemblyReference.cache
  src/FutMobile/FutMobile/obj/Release/FutMobile.dll
  src/FutMobile/FutMobile/obj/Release/FutMobile.pdb
Labels: Component, Database, bug, cloud, documentation, enhancement
